import 'dart:math';

class Quote {
  static Map<String, String> quotes = {
    "The way to get started is to quit talking and begin doing.": "Walt Disney",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.": "Winston Churchill",
    "The future belongs to those who believe in the beauty of their dreams.": "Eleanor Roosevelt",
    "In the middle of every difficulty lies opportunity.": "Albert Einstein",
    "Believe you can and you're halfway there.": "Theodore Roosevelt",
    "The only way to do great work is to love what you do.": "Steve Jobs",
    "Do what you have to do until you can do what you want to do.": "Oprah Winfrey",
    "Whether you think you can or you think you can't, you're right.": "Henry Ford",
    "It always seems impossible until it's done.": "Nelson Mandela",
    "It does not matter how slowly you go as long as you do not stop.": "Confucius",
    "Setting goals is the first step in turning the invisible into the visible.": "Tony Robbins",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.": "Vince Lombardi",
    "You're off to great places! Today is your day! Your mountain is waiting, so get on your way!": "Dr. Seuss",
    "The secret of getting ahead is getting started.": "Mark Twain",
    "You will face many defeats in life, but never let yourself be defeated.": "Maya Angelou",
    "Your attitude, not your aptitude, will determine your altitude.": "Zig Ziglar",
    "Things work out best for those who make the best of how things work out.": "John Wooden",
    "Either you run the day or the day runs you.": "Jim Rohn",
    "The best way to predict the future is to create it.": "Abraham Lincoln",
    "Keep your face to the sunshine and you cannot see a shadow.": "Helen Keller",
    "Energy and persistence conquer all things.": "Benjamin Franklin",
    "You miss 100% of the shots you don't take.": "Wayne Gretzky",
    "I've failed over and over and over again in my life, and that is why I succeed.": "Michael Jordan",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.": "Ralph Waldo Emerson",
    "Shoot for the moon. Even if you miss, you'll land among the stars.": "Les Brown",
    "Happiness is not something ready made. It comes from your own actions.": "Dalai Lama",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.": "Aristotle",
    "It is our choices that show what we truly are, far more than our abilities.": "J.K. Rowling",
    "Every great dream begins with a dreamer.": "Harriet Tubman",
    "The successful warrior is the average man, with laser-like focus.": "Bruce Lee",
    "In the midst of chaos, there is also opportunity.": "Sun Tzu",
    "Go confidently in the direction of your dreams. Live the life you have imagined.": "Henry David Thoreau",
    "It's hard to beat a person who never gives up.": "Babe Ruth",
    "The most effective way to do it, is to do it.": "Amelia Earhart",
    "Genius is one percent inspiration and ninety-nine percent perspiration.": "Thomas Edison",
    "Tough times never last, but tough people do.": "Robert H. Schuller",
    "Change your thoughts and you change your world.": "Norman Vincent Peale",
    "Everything you can imagine is real.": "Pablo Picasso",
    "Done is better than perfect.": "Sheryl Sandberg",
    "Nothing in life is to be feared, it is only to be understood.": "Marie Curie",
    "The future rewards those who press on. I don’t have time to feel sorry for myself.": "Barack Obama",
    "What you seek is seeking you.": "Rumi",
    "You are never too old to set another goal or to dream a new dream.": "C.S. Lewis",
    "Set your goals high, and don’t stop till you get there.": "Bo Jackson",
    "The best way to predict your future is to create it.": "Peter Drucker",
    "Be uncommon amongst uncommon people.": "David Goggins",
    "A champion is defined not by their wins but by how they can recover when they fall.": "Serena Williams",
    "Let us make our future now, and let us make our dreams tomorrow's reality.": "Malala Yousafzai",
    "Each person must live their life as a model for others.": "Rosa Parks",
    "You can choose courage, or you can choose comfort, but you cannot choose both.": "Brene Brown",
    "Don't wait for perfection. Start today.": "Jon Acuff",
    "Success is your duty, obligation, and responsibility.": "Grant Cardone",
    "Waiting for perfect is never as smart as making progress.": "Seth Godin",
    "Enthusiasm is common. Endurance is rare.": "Angela Duckworth",
    "The secret to success is good leadership, and good leadership is all about making the lives of your team members better.": "Tony Dungy",
    "The key is in not spending time, but in investing it.": "Stephen Covey",
    "Make your life a masterpiece; imagine no limitations on what you can be, have, or do.": "Brian Tracy",
    "Don't worry about failures; worry about the chances you miss when you don't even try.": "Jack Canfield",
    "Don't count the days, make the days count.": "Muhammad Ali",
    "Working hard for something we don't care about is called stress; working hard for something we love is called passion.": "Simon Sinek",
    "Do not be embarrassed by your failures, learn from them and start again.": "Richard Branson",
    "I never dreamed about success. I worked for it.": "Estée Lauder",
    "Life is 10% what happens to us and 90% how we react to it.": "Charles Swindoll",
    "Say yes, and you'll figure it out afterwards.": "Tina Fey",
    "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.": "Reid Hoffman",
    "Do or do not. There is no try.": "Yoda",
    "Great things come from hard work and perseverance. No excuses.": "Kobe Bryant",
    "Do not allow people to dim your shine because they are blinded. Tell them to put some sunglasses on.": "Lady Gaga",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world.": "Anne Frank",
    "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself.": "Bill Gates",
    "If you double the number of experiments you do per year, you're going to double your inventiveness.": "Jeff Bezos",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.": "Albert Schweitzer",
    "Life isn’t about finding yourself. Life is about creating yourself.": "George Bernard Shaw",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.": "Roy T. Bennett",
    "Whatever the mind can conceive and believe, it can achieve.": "Napoleon Hill",
    "I am not what happened to me, I am what I choose to become.": "Carl Jung",
    "I'm a great believer in luck, and I find the harder I work the more I have of it.": "Thomas Jefferson",
    "When we are no longer able to change a situation, we are challenged to change ourselves.": "Viktor Frankl",
    "At the end of the day, it’s not about what you have or even what you’ve accomplished. It’s about who you’ve lifted up, who you’ve made better. It’s about what you’ve given back.": "Denzel Washington",
    "It is never too late to be what you might have been.": "George Eliot",
    "If there is no struggle, there is no progress.": "Frederick Douglass",
    "Everyone thinks of changing the world, but no one thinks of changing himself.": "Leo Tolstoy",
    "You do not rise to the level of your goals. You fall to the level of your systems.": "James Clear",
    "Act as if what you do makes a difference. It does.": "William James",
    "The question isn’t who is going to let me; it’s who is going to stop me.": "Ayn Rand",
    "It’s through mistakes that you actually can grow. You have to get bad in order to get good.": "J.J. Abrams",
    "I may not have gone where I intended to go, but I think I have ended up where I needed to be.": "Douglas Adams",
    "The best way to predict the future is to create it.": "Peter Drucker",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.": "Winston Churchill",
    "Do not pray for an easy life, pray for the strength to endure a difficult one.": "Bruce Lee",
    "Opportunities don’t happen. You create them.": "Chris Grosser",
    "Victory is reserved for those who are willing to pay its price.": "Sun Tzu",
    "Don’t count the days, make the days count.": "Muhammad Ali",
    "A goal without a plan is just a wish.": "Antoine de Saint-Exupéry",
    "The successful warrior is the average man, with laser-like focus.": "Bruce Lee",
    "In business, the competition will bite you if you keep running; if you stand still, they will swallow you.": "William Knudsen",
    "The way to get started is to quit talking and begin doing.": "Walt Disney",
    "Every battle is won before it is fought.": "Sun Tzu",
    "Success usually comes to those who are too busy to be looking for it.": "Henry David Thoreau",
    "Knowing is not enough, we must apply. Willing is not enough, we must do.": "Bruce Lee",
    "It’s not about ideas. It’s about making ideas happen.": "Scott Belsky",
    "The harder the battle, the sweeter the victory.": "Les Brown",
    "Don’t be afraid to give up the good to go for the great.": "John D. Rockefeller",
    "Fall seven times and stand up eight.": "Japanese Proverb",
    "Great things in business are never done by one person; they’re done by a team of people.": "Steve Jobs",
    "If you spend too much time thinking about a thing, you'll never get it done.": "Bruce Lee",
    "In the middle of difficulty lies opportunity.": "Albert Einstein",
    "Sweat more during peace: bleed less during war.": "Sun Tzu",
    "A black belt is a white belt who never gave up.": "Unknown",
    "If you want to conquer fear, don't sit home and think about it. Go out and get busy.": "Dale Carnegie",
    "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.": "Bruce Lee",
    "Don’t wish it were easier. Wish you were better.": "Jim Rohn",
    "When something is important enough, you do it even if the odds are not in your favor.": "Elon Musk",
    "It does not matter how slowly you go as long as you do not stop.": "Confucius",
    "Business opportunities are like buses, there’s always another one coming.": "Richard Branson",
    "If you don’t drive your business, you will be driven out of business.": "B. C. Forbes",
    "We generate fears while we sit. We overcome them by action.": "Dr. Henry Link",
    "Tactics without strategy is the noise before defeat.": "Sun Tzu",
    "Success is walking from failure to failure with no loss of enthusiasm.": "Winston Churchill",
    "The journey of a thousand miles begins with one step.": "Lao Tzu",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.": "David Brinkley",
    "To hell with circumstances; I create opportunities.": "Bruce Lee",
    "Failure is simply the opportunity to begin again, this time more intelligently.": "Henry Ford",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.": "Jim Rohn",
    "Don’t wait. The time will never be just right.": "Napoleon Hill",
    "Innovation distinguishes between a leader and a follower.": "Steve Jobs",
    "If opportunity doesn’t knock, build a door.": "Milton Berle",
    "It always seems impossible until it’s done.": "Nelson Mandela",
    "Whether you think you can or think you can’t, you’re right.": "Henry Ford",
    "The supreme art of war is to subdue the enemy without fighting.": "Sun Tzu",
    "Do what you can, with what you have, where you are.": "Theodore Roosevelt",
    "Perseverance is failing 19 times and succeeding the 20th.": "Julie Andrews",
    "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.": "Alexander the Great",
    "Courage is resistance to fear, mastery of fear—not absence of fear.": "Mark Twain",
    "You miss 100% of the shots you don’t take.": "Wayne Gretzky",
    "Do not be embarrassed by your failures, learn from them and start again.": "Richard Branson",
    "Fortune favors the bold.": "Latin Proverb",
    "A leader is one who knows the way, goes the way, and shows the way.": "John C. Maxwell",
    "The more you sweat in training, the less you bleed in battle.": "Richard Marcinko",
    "Vision without execution is just hallucination.": "Thomas Edison",
    "The only limit to our realization of tomorrow is our doubts of today.": "Franklin D. Roosevelt",
    "Hardships often prepare ordinary people for an extraordinary destiny.": "C.S. Lewis",
    "The only way to do great work is to love what you do.": "Steve Jobs",
    "Discipline equals freedom.": "Jocko Willink",
    "Winners never quit and quitters never win.": "Vince Lombardi",
    "Adapt what is useful, reject what is useless, and add what is specifically your own.": "Bruce Lee",
    "An ounce of action is worth a ton of theory.": "Ralph Waldo Emerson",
    "There is no substitute for hard work.": "Thomas Edison",
    "You have to be fast on your feet and adaptive or else a strategy is useless.": "Charles de Gaulle",
    "He who is not courageous enough to take risks will accomplish nothing in life.": "Muhammad Ali",
    "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.": "Benjamin Franklin",
    "What gets measured gets managed.": "Peter Drucker",
    "The difference between ordinary and extraordinary is that little extra.": "Jimmy Johnson",
    "Success is how high you bounce when you hit bottom.": "George S. Patton",
    "You can’t build a reputation on what you are going to do.": "Henry Ford",
    "The only easy day was yesterday.": "Navy SEALs Motto",
    "It’s not whether you get knocked down, it’s whether you get up.": "Vince Lombardi",
    "The secret of getting ahead is getting started.": "Mark Twain",
    "If you're going through hell, keep going.": "Winston Churchill",
    "Do one thing every day that scares you.": "Eleanor Roosevelt",
    "Some people want it to happen, some wish it would happen, others make it happen.": "Michael Jordan",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.": "James Cameron",
    "Strength does not come from physical capacity. It comes from an indomitable will.": "Mahatma Gandhi",
    "Success is not the absence of failure; it's the persistence through failure.": "Aisha Tyler",
    "Act as if what you do makes a difference. It does.": "William James",
    "A smooth sea never made a skilled sailor.": "Franklin D. Roosevelt",
    "Champions keep playing until they get it right.": "Billie Jean King",
    "Leadership is not about being in charge. It is about taking care of those in your charge.": "Simon Sinek",
    "Fall in love with the process and the results will come.": "Eric Thomas",
    "Success doesn’t just find you. You have to go out and get it.": "Unknown",
    "A warrior’s greatest weapon is patience.": "Unknown",
    "The more you practice, the better you get, the luckier you become.": "Gary Player",
    "Leadership and learning are indispensable to each other.": "John F. Kennedy",
    "The brave may not live forever—but the cautious do not live at all.": "Richard Branson",
    "Do not let what you cannot do interfere with what you can do.": "John Wooden",
    "Keep your fears to yourself, but share your courage with others.": "Robert Louis Stevenson",
    "Doubt kills more dreams than failure ever will.": "Suzy Kassem",
    "Success is never owned, it’s rented—and the rent is due every day.": "Rory Vaden",
    "Train hard, fight easy.": "Alexander Suvorov",
    "A champion is someone who gets up when they can’t.": "Jack Dempsey",
    "Success is simple. Do what's right, the right way, at the right time.": "Arnold H. Glasow",
    "Fortune sides with him who dares.": "Virgil",
    "A true warrior fights not because he hates what is in front of him, but because he loves what is behind him.": "G.K. Chesterton"
  };

  late String quote;
  late String author;

  Quote() {
    int rn = Random().nextInt(quotes.length);
    quote = quotes.keys.elementAt(rn);
    author = quotes[quote]!;
  }
}